import {ProgramListRowData} from "../components/ProgramRow";

export const dummyPrograms: ProgramListRowData[] = [
  {
    id: "prog_1",
    examType: "utme",
    logoUrl: "https://picsum.photos/seed/utme/56",
    teacherName: "Matthew James",
    rating: "4.7",
    reviewCount: "5.2k",
    title: "Universal Tertiary Matriculation Exam - UTME",
    tags: ["Exam", "School Leaving"],
    extraTagsCount: 8,
    status: "live",
    price: 5345,
    originalPrice: 3500,
    perSubjectPrice: 24500,
    currency: "₦",
    link: "https://mcc.com/prog_1",
    instructor: "MCC Tutors",
    description:
      "JAMB UTME is a mandatory computer-based test for admission into tertiary institutions in Nigeria. Prepare for JAMB UTME with our comprehensive exam prep courses, covering all subjects and topics required for the exam.",
    imgBig: "/assets/images/courses/uiux-big.jpg",
    imgSmall: "/assets/images/courses/uiux-small.jpg",
  },
  {
    id: "prog_2",
    examType: "waec",
    logoUrl: "https://picsum.photos/seed/waec1/56",
    teacherName: "Anna Williams",
    rating: "4.7",
    reviewCount: "5.2k",
    title: "West African Examination Council - WAEC",
    tags: ["Exam", "School Leaving"],
    extraTagsCount: 8,
    status: "live",
    price: "172,345",
    perSubjectPrice: "24,500",
    currency: "₦",
    link: "https://mcc.com/prog_2",
  },
  {
    id: "prog_3",
    examType: "waec",
    logoUrl: "https://picsum.photos/seed/waec2/56",
    teacherName: "Becky Gray",
    rating: "4.7",
    reviewCount: "5.2k",
    title: "West African Examination Council - WAEC",
    tags: ["Exam", "School Leaving"],
    extraTagsCount: 8,
    status: "live",
    price: "592,345",
    perSubjectPrice: "95,899",
    currency: "₦",
    link: "https://mcc.com/prog_3",
  },
  {
    id: "prog_4",
    examType: "waec",
    // no logoUrl on purpose, to test the fallback icon state
    teacherName: "Jason Thompson",
    rating: "4.7",
    reviewCount: "5.2k",
    title: "West African Examination Council - WAEC",
    tags: ["Exam", "School Leaving"],
    extraTagsCount: 8,
    status: "draft",
    price: "290,345",
    perSubjectPrice: "75,900",
    currency: "₦",
    link: "https://mcc.com/prog_4",
  },
  {
    id: "prog_5",
    examType: "waec",
    logoUrl: "https://picsum.photos/seed/waec4/56",
    teacherName: "Conner Gates",
    rating: "4.7",
    reviewCount: "5.2k",
    title: "West African Examination Council - WAEC",
    tags: ["Exam", "School Leaving"],
    extraTagsCount: 8,
    status: "draft",
    price: "290,345",
    perSubjectPrice: "75,900",
    currency: "₦",
    link: "https://mcc.com/prog_5",
  },
  {
    id: "prog_6",
    examType: "waec",
    logoUrl: "https://picsum.photos/seed/waec5/56",
    teacherName: "Ben Woods",
    rating: "4.7",
    reviewCount: "5.2k",
    title: "West African Examination Council - WAEC",
    tags: ["Exam", "School Leaving"],
    extraTagsCount: 8,
    status: "live",
    price: "290,345",
    perSubjectPrice: "75,900",
    currency: "₦",
    link: "https://mcc.com/prog_6",
  },
];

// Empty-state test case
export const dummyProgramsEmpty: ProgramListRowData[] = [];
