import type { Field } from "./fields";
import type { BlockDefinition } from "./types";

// Shorthands, so each block below reads as its list of fields.
const text = (key: string, label: string, help?: string, maxLength = 200): Field => ({ kind: "text", key, label, help, maxLength });
const area = (key: string, label: string, help?: string, maxLength = 1000): Field => ({ kind: "textarea", key, label, help, maxLength });
const url = (key: string, label: string, help?: string): Field => ({ kind: "url", key, label, help });
const image = (key: string, label: string, help?: string): Field => ({ kind: "image", key, label, help });
const toggle = (key: string, label: string, help?: string): Field => ({ kind: "toggle", key, label, help });
const strings = (key: string, label: string, itemLabel: string, max = 8): Field => ({ kind: "strings", key, label, itemLabel, max });

const SIGNUP_HELP = "Where the button goes. /signup is the student sign-up page.";

export const BLOCKS: BlockDefinition[] = [
  {
    type: "hero",
    label: "Hero",
    description: "The opening promise, the main sign-up button and the phone mockup.",
    icon: "lucide:sparkles",
    anchor: "top",
    fields: [
      text("eyebrow", "Badge text", "The small pill above the headline (next to a \"New\" tag)."),
      text("headline_lead", "Headline, first part"),
      text("headline_emph", "Headline, highlighted part", "Shown in the purple gradient."),
      area("body", "Intro paragraph"),
      text("cta_label", "Main button label"),
      url("cta_href", "Main button link", SIGNUP_HELP),
      text("parent_label", "Parent button label"),
      url("parent_href", "Parent button link", "#parents scrolls to the parents section."),
      text("login_prompt", "Log-in prompt", "e.g. \"Already have an account?\""),
      text("login_label", "Log-in link label"),
      url("login_href", "Log-in link"),
      strings("ticks", "Reassurance ticks", "Tick", 5),
    ],
    defaults: {
      eyebrow: "Meet Brainy, your AI study buddy",
      headline_lead: "Walk into your exam",
      headline_emph: "ready.",
      body: "Prep for JAMB, WAEC, NECO, IGCSE and more with lessons, practice tests and Brainy, your AI study buddy. Then a real person calls you, free, to help you pick the right path.",
      cta_label: "Get started free",
      cta_href: "/signup",
      parent_label: "I'm a parent",
      parent_href: "#parents",
      login_prompt: "Already have an account?",
      login_label: "Log in",
      login_href: "/login",
      ticks: ["Free to sign up", "Free onboarding call", "Light on data"],
    },
  },
  {
    type: "exams",
    label: "Exams",
    description: "Searchable cards for each exam you prepare students for.",
    icon: "lucide:graduation-cap",
    anchor: "exams",
    fields: [
      text("eyebrow", "Small heading"),
      text("headline", "Headline"),
      area("body", "Paragraph"),
      text("cta_label", "Link label"),
      url("cta_href", "Link"),
      {
        kind: "list", key: "exams", label: "Exams", itemLabel: "Exam", titleKey: "code", max: 24,
        fields: [
          text("code", "Short name", "Big text on the card, e.g. JAMB.", 24),
          text("name", "Full name", "e.g. UTME", 80),
          text("note", "Short description", "e.g. University entry · Nigeria", 80),
          text("tags", "Search words", "Subjects a student might type, separated by spaces.", 200),
          url("href", "Card link", SIGNUP_HELP),
        ],
      },
    ],
    defaults: {
      eyebrow: "Exam prep",
      headline: "Pick your exam. We'll take it from there.",
      body: "One programme per exam and subject: lectures, module quizzes, practice questions with explanations and a timed test with a pass mark.",
      cta_label: "All exams and subjects",
      cta_href: "/signup",
      exams: [
        { code: "JAMB", name: "UTME", note: "University entry · Nigeria", tags: "english maths physics chemistry biology economics government literature", href: "/signup" },
        { code: "WAEC", name: "WASSCE", note: "School certificate · West Africa", tags: "english maths physics chemistry biology economics", href: "/signup" },
        { code: "NECO", name: "SSCE", note: "School certificate · Nigeria", tags: "english maths physics chemistry biology", href: "/signup" },
        { code: "IGCSE", name: "Cambridge & Edexcel", note: "International · Ages 14–16", tags: "maths physics chemistry biology english", href: "/signup" },
        { code: "A-Levels", name: "AS & A Level", note: "International · Ages 16–18", tags: "maths physics chemistry biology economics", href: "/signup" },
        { code: "SAT", name: "Digital SAT", note: "US university entry", tags: "maths reading writing", href: "/signup" },
        { code: "PMP", name: "Project Management Professional", note: "Professional certificate", tags: "project management career", href: "/signup" },
        { code: "DELF", name: "DELF & DALF", note: "French language diplomas", tags: "french language", href: "/signup" },
      ],
    },
  },
  {
    type: "steps",
    label: "How it works",
    description: "Numbered steps from sign-up to exam day. One step can be highlighted.",
    icon: "lucide:list-ordered",
    anchor: "how",
    fields: [
      text("eyebrow", "Small heading"),
      text("headline", "Headline"),
      area("body", "Paragraph"),
      {
        kind: "list", key: "steps", label: "Steps", itemLabel: "Step", titleKey: "title", max: 6,
        fields: [
          text("title", "Title"),
          area("body", "Description", undefined, 400),
          toggle("highlight", "Highlight this step", "Shows it as a purple card with a \"free, a real person\" tag."),
        ],
      },
      text("cta_label", "Button label"),
      url("cta_href", "Button link", SIGNUP_HELP),
      text("note", "Note next to the button"),
    ],
    defaults: {
      eyebrow: "How it works",
      headline: "Four steps from sign-up to exam day.",
      body: "You won't be left to figure it out alone. A real person helps you start, then the app keeps you on track.",
      steps: [
        { title: "Create your free account", body: "About two minutes on your phone. No card needed.", highlight: false },
        { title: "Get a free call to pick your path", body: "A Customer Relations Associate calls you, learns your goals and helps you choose the right programme or course.", highlight: true },
        { title: "Learn and practise", body: "Lessons, module quizzes, timed tests, weekly live classes with your teacher, and Brainy whenever you're stuck.", highlight: false },
        { title: "See yourself improve", body: "Streaks, rewards and certificates show how far you've come. Parents can follow along in their own app.", highlight: false },
      ],
      cta_label: "Get started free",
      cta_href: "/signup",
      note: "Your free call is booked right after sign-up.",
    },
  },
  {
    type: "brainy",
    label: "Brainy (AI study buddy)",
    description: "A dark section showing the AI companion, with a chat and flashcard mockup.",
    icon: "lucide:bot",
    anchor: "brainy",
    fields: [
      text("eyebrow", "Small heading"),
      text("headline", "Headline"),
      area("body", "Paragraph"),
      strings("inputs", "\"Works with\" chips", "Chip", 8),
      {
        kind: "list", key: "features", label: "Features", itemLabel: "Feature", titleKey: "title", max: 5,
        fields: [text("title", "Title"), area("body", "Description", undefined, 300)],
      },
      text("cta_label", "Button label"),
      url("cta_href", "Button link", SIGNUP_HELP),
    ],
    defaults: {
      eyebrow: "Meet Brainy",
      headline: "Snap your notes. Get flashcards.",
      body: "Brainy is your AI study companion. Ask it anything, or give it your notes and it turns them into study sets you'll actually remember.",
      inputs: ["PDF", "Word", "PowerPoint", "Photo of a page", "Voice note"],
      features: [
        { title: "Ask anything, any time", body: "Stuck at midnight? Get a clear, step-by-step answer in plain English." },
        { title: "Notes in, study sets out", body: "Upload, paste or snap your notes. Brainy builds flashcards and quizzes from them." },
        { title: "Remember it on exam day", body: "Spaced repetition brings each card back just before you'd forget it." },
      ],
      cta_label: "Try Brainy free",
      cta_href: "/signup",
    },
  },
  {
    type: "practice",
    label: "Practice and tests",
    description: "Timed quizzes, explained answers and pass marks, with a quiz mockup.",
    icon: "lucide:timer",
    anchor: "practice",
    fields: [
      text("eyebrow", "Small heading"),
      text("headline", "Headline"),
      area("body", "Paragraph"),
      {
        kind: "list", key: "features", label: "Features", itemLabel: "Feature", titleKey: "title", max: 5,
        fields: [text("title", "Title"), area("body", "Description", undefined, 300)],
      },
      text("cta_label", "Button label"),
      url("cta_href", "Button link", SIGNUP_HELP),
    ],
    defaults: {
      eyebrow: "Practice and tests",
      headline: "Practise like it's the real exam.",
      body: "Quizzes after every module, a deep bank of practice questions and full timed mocks. Wrong answers become lessons, not stress.",
      features: [
        { title: "Timed, like the real thing", body: "Practise against the clock so exam day timing doesn't catch you off guard." },
        { title: "Every answer explained", body: "Got it wrong? See exactly why, and the method that gets it right." },
        { title: "Pass marks you can aim for", body: "Each module ends in a test with a pass mark, so you know when you're ready to move on." },
      ],
      cta_label: "Try a free practice test",
      cta_href: "/signup",
    },
  },
  {
    type: "humans",
    label: "Real people (onboarding call and live classes)",
    description: "Two cards with photos: the free onboarding call and weekly live classes.",
    icon: "lucide:users",
    anchor: "teachers",
    fields: [
      text("eyebrow", "Small heading"),
      text("headline", "Headline"),
      area("body", "Paragraph"),
      text("call_title", "Onboarding call: title"),
      area("call_body", "Onboarding call: description", undefined, 400),
      image("call_image_url", "Onboarding call: photo", "A real member of staff works best. Leave empty for a soft purple panel."),
      text("class_title", "Live classes: title"),
      area("class_body", "Live classes: description", undefined, 400),
      image("class_image_url", "Live classes: photo", "Leave empty for a soft purple panel."),
      strings("trust", "Trust points", "Point", 5),
    ],
    defaults: {
      eyebrow: "Real people, not just an app",
      headline: "Someone in your corner from day one.",
      body: "Apps are great. People are better. Every student gets a free call when they join, and a teacher they meet every week.",
      call_title: "Your free onboarding call",
      call_body: "A Customer Relations Associate calls to understand your goals and helps you pick the right programme or course. No pressure, no sales script.",
      call_image_url: "",
      class_title: "Live classes with your own teacher",
      class_body: "You're assigned a vetted teacher. Join them weekly to ask questions, go over tough topics and stay on track.",
      class_image_url: "",
      trust: ["Every teacher is vetted", "A weekly class with your own teacher", "A real person to help you start"],
    },
  },
  {
    type: "courses",
    label: "Courses",
    description: "A filterable grid of course cards (Free / Paid).",
    icon: "lucide:library",
    anchor: "courses",
    fields: [
      text("eyebrow", "Small heading"),
      text("headline", "Headline"),
      area("body", "Paragraph"),
      {
        kind: "list", key: "courses", label: "Courses", itemLabel: "Course", titleKey: "title", max: 12,
        fields: [
          text("title", "Course name"),
          text("category", "Category", "Small caps label, e.g. TECH.", 40),
          text("glyph", "Card artwork text", "A short word or symbol drawn on the card, e.g. </>", 16),
          toggle("free", "Free course"),
          text("price_label", "Price text", "Shown for paid courses, e.g. ₦15,000.", 40),
          text("byline", "Teacher and lessons line", "e.g. Taught by Mrs Okafor · 24 lessons.", 80),
          image("image_url", "Cover image (optional)"),
          url("href", "Course link", "Where the card goes."),
        ],
      },
      text("cta_label", "Button label"),
      url("cta_href", "Button link"),
    ],
    defaults: {
      eyebrow: "Courses beyond exams",
      headline: "Pick up a new skill while you're at it.",
      body: "Short courses from vetted teachers: coding, languages, money skills and more. Plenty are free.",
      courses: [],
      cta_label: "Browse all courses",
      cta_href: "/signup",
    },
  },
  {
    type: "parents",
    label: "For parents",
    description: "Reassurance for parents, with the parent app mockup.",
    icon: "lucide:heart-handshake",
    anchor: "parents",
    fields: [
      text("eyebrow", "Badge text"),
      text("headline", "Headline"),
      area("body", "Paragraph"),
      {
        kind: "list", key: "pillars", label: "Reassurance cards", itemLabel: "Card", titleKey: "title", max: 4,
        fields: [text("title", "Title"), area("body", "Description", undefined, 300)],
      },
      text("cta_label", "Main button label"),
      url("cta_href", "Main button link", "Where a parent goes to set up. /go/parent/signup opens the parent app."),
      text("secondary_label", "Second link label"),
      url("secondary_href", "Second link"),
    ],
    defaults: {
      eyebrow: "For parents",
      headline: "See the progress, not just the fees.",
      body: "The parent app shows what your child studied and how their quizzes went. No guessing, no chasing.",
      pillars: [
        { title: "Progress you can see", body: "Study time, quiz and test results and live class attendance, in one place." },
        { title: "Safe and supervised", body: "Every teacher is vetted, and live classes are booked and joined from your child's MCC account." },
        { title: "Value for money", body: "Prices in Naira, paid by card through Flutterwave. Lots of courses are free." },
      ],
      cta_label: "I'm a parent",
      cta_href: "/go/parent/signup",
      secondary_label: "How the parent app works",
      secondary_href: "#how",
    },
  },
  {
    type: "proof",
    label: "Stories and results",
    description: "Student and parent quotes and a row of results. Add only real, verified ones.",
    icon: "lucide:message-square-quote",
    anchor: "stories",
    fields: [
      text("eyebrow", "Small heading"),
      text("headline", "Headline"),
      {
        kind: "list", key: "quotes", label: "Quotes", itemLabel: "Quote", titleKey: "who", max: 6,
        fields: [
          area("text", "Quote", "One or two sentences, in their words.", 400),
          text("who", "Name and role", "e.g. Amaka, student", 80),
          text("meta", "Detail", "e.g. JAMB · 2026 · Lagos", 80),
        ],
      },
      {
        kind: "list", key: "results", label: "Results", itemLabel: "Result", titleKey: "label", max: 4,
        fields: [text("value", "Figure", "Only a figure you can prove, e.g. 92%.", 24), text("label", "What it measures", undefined, 120)],
      },
    ],
    defaults: {
      eyebrow: "Stories",
      headline: "Students and parents, in their own words.",
      quotes: [],
      results: [],
    },
  },
  {
    type: "faq",
    label: "FAQ",
    description: "Questions and answers that open and close.",
    icon: "lucide:circle-help",
    anchor: "faq",
    fields: [
      text("eyebrow", "Small heading"),
      text("headline", "Headline"),
      area("body", "Paragraph"),
      text("cta_label", "Button label"),
      url("cta_href", "Button link", "e.g. #contact, or mailto:hello@yourdomain.com."),
      {
        kind: "list", key: "items", label: "Questions", itemLabel: "Question", titleKey: "q", max: 16,
        fields: [text("q", "Question", undefined, 160), area("a", "Answer", undefined, 1200)],
      },
    ],
    defaults: {
      eyebrow: "FAQ",
      headline: "Questions? We've got you.",
      body: "Can't find your answer? Our team is happy to help.",
      cta_label: "Talk to us",
      cta_href: "#contact",
      items: [
        { q: "How much does it cost?", a: "Creating an account is free, the onboarding call is free, and many courses are free. Paid programmes are priced in Naira and you pay by card through Flutterwave." },
        { q: "Which exams and subjects do you cover?", a: "JAMB, WAEC, NECO, IGCSE, A-Levels, SAT, PMP, DELF and DALF, with one programme per exam and subject. We also offer courses in skills like coding, languages and personal finance." },
        { q: "How does the free call work?", a: "Right after you sign up, you pick a time. A Customer Relations Associate calls you, asks about your goals and helps you choose the right programme. It's free and there's no obligation to buy." },
        { q: "Will it work on my phone and data?", a: "Yes. MCC works in your phone's browser and is built to keep data use low." },
        { q: "How do parents follow progress?", a: "Parents use the parent app, linked to their child's account, to see study time, quiz results and live class attendance." },
      ],
    },
  },
  {
    type: "cta",
    label: "Closing banner",
    description: "A bold purple banner with the final sign-up button.",
    icon: "lucide:megaphone",
    anchor: "start",
    fields: [
      text("headline", "Headline"),
      area("body", "Paragraph"),
      text("cta_label", "Main button label"),
      url("cta_href", "Main button link", SIGNUP_HELP),
      text("login_label", "Log-in button label"),
      url("login_href", "Log-in button link"),
      text("parent_label", "Parent link label"),
      url("parent_href", "Parent link"),
    ],
    defaults: {
      headline: "Your exam won't wait. Start today, free.",
      body: "Create your account in about two minutes, then book your free call. We'll help you with the rest.",
      cta_label: "Get started free",
      cta_href: "/signup",
      login_label: "Log in",
      login_href: "/login",
      parent_label: "I'm a parent: set up for my child",
      parent_href: "/go/parent/signup",
    },
  },
];

export const BLOCK_BY_TYPE: Record<string, BlockDefinition> = Object.fromEntries(BLOCKS.map((b) => [b.type, b]));

export function blockDefinition(type: string): BlockDefinition | undefined {
  return BLOCK_BY_TYPE[type];
}
