import { FormSteps } from "../types/formTypes";

// Fields marked "mocked" below have no backend endpoint behind them yet --
// see backend/docs/teacher-onboarding-backend-todo.md. Availability (step
// "availability") and the profile_photo field (step "teaching_profile") are
// the two real, backend-wired exceptions.
export const formSteps: FormSteps = [
  {
    id: "identity",
    title: "Verify your identity",
    question: "Verify your identity",
    inputType: "mixed",
    fields: [
      {
        id: "id_type",
        inputType: "select",
        question: "What type of ID are you providing?",
        options: [
          { value: "nin", label: "National ID (NIN)" },
          { value: "drivers_license", label: "Driver's License" },
          { value: "passport", label: "International Passport" },
          { value: "voters_card", label: "Voter's Card" },
        ],
        validation: { required: "Please select an ID type" },
      },
      {
        id: "id_number",
        inputType: "text",
        question: "ID number",
        validation: { required: "Enter your ID number" },
      },
      {
        id: "id_document",
        inputType: "file",
        question: "Upload your ID document",
        accept: "image/*,.pdf",
        helpText: "Clear photo or scan, JPG/PNG/PDF, max 5MB.",
        validation: { required: "Please upload your ID document" },
      },
      {
        id: "teaching_certificate",
        inputType: "file",
        question: "Teaching certificate or license (optional)",
        accept: "image/*,.pdf",
        validation: {},
      },
      {
        id: "selfie_verification",
        inputType: "file",
        question: "Verification selfie",
        accept: "image/*",
        helpText: "We'll match this to your ID photo.",
        validation: { required: "Please upload a verification selfie" },
      },
    ],
  },
  {
    id: "subjects",
    inputType: "tile-multi",
    fieldId: "subjects",
    question: "Which subjects do you teach?",
    options: [
      { value: "mathematics", label: "Mathematics", icon: "mdi:calculator-variant" },
      { value: "english_language", label: "English Language", icon: "mdi:book-alphabet" },
      { value: "physics", label: "Physics", icon: "mdi:atom" },
      { value: "chemistry", label: "Chemistry", icon: "mdi:flask" },
      { value: "biology", label: "Biology", icon: "mdi:leaf" },
      { value: "economics", label: "Economics", icon: "mdi:chart-line" },
      { value: "government", label: "Government", icon: "mdi:bank" },
      { value: "literature_in_english", label: "Literature-in-English", icon: "mdi:book-open-page-variant" },
      { value: "geography", label: "Geography", icon: "mdi:earth" },
      { value: "further_mathematics", label: "Further Mathematics", icon: "mdi:sigma" },
      { value: "agricultural_science", label: "Agricultural Science", icon: "mdi:tractor" },
      { value: "computer_science", label: "Computer Science", icon: "mdi:laptop" },
      { value: "financial_accounting", label: "Financial Accounting", icon: "mdi:calculator" },
      { value: "french", label: "French", icon: "mdi:translate" },
      { value: "other", label: "Other", icon: "mdi:dots-horizontal" },
    ],
    validation: { required: "Select at least one subject" },
  },
  {
    id: "qualifications",
    title: "Qualifications & experience",
    question: "Qualifications & experience",
    inputType: "mixed",
    fields: [
      {
        id: "highest_qualification",
        inputType: "select",
        question: "Highest qualification",
        options: [
          { value: "ssce", label: "SSCE/WAEC only" },
          { value: "ond", label: "OND" },
          { value: "nce", label: "NCE" },
          { value: "hnd", label: "HND" },
          { value: "bachelors", label: "Bachelor's Degree (B.Sc/B.A/B.Ed)" },
          { value: "masters", label: "Master's Degree" },
          { value: "pgde", label: "PGDE" },
          { value: "phd", label: "PhD" },
          { value: "other", label: "Other" },
        ],
        validation: { required: "Select your highest qualification" },
      },
      {
        id: "institution",
        inputType: "text",
        question: "Which institution did you attend?",
        placeholder: "e.g. University of Lagos",
        validation: { required: "Enter your institution" },
      },
      {
        id: "graduation_year",
        inputType: "text",
        htmlType: "number",
        question: "Graduation year",
        placeholder: "e.g. 2015",
        validation: {
          required: "Enter your graduation year",
          pattern: { value: /^(19[5-9]\d|20[0-2]\d)$/, message: "Enter a valid year" },
        },
      },
      {
        id: "years_of_teaching_experience",
        inputType: "select",
        question: "Years of teaching experience",
        options: [
          { value: "lt1", label: "Less than 1 year" },
          { value: "1to2", label: "1–2 years" },
          { value: "3to5", label: "3–5 years" },
          { value: "6to10", label: "6–10 years" },
          { value: "10plus", label: "10+ years" },
        ],
        validation: { required: "Select your experience range" },
      },
      {
        id: "teaching_experience_summary",
        inputType: "text",
        htmlType: "textarea",
        question: "Tell us about your teaching experience",
        placeholder: "Where you've taught, subjects, grade levels, notable achievements…",
        validation: {},
      },
    ],
  },
  {
    id: "curriculum",
    title: "Curriculum & grade levels",
    question: "Curriculum & grade levels",
    inputType: "mixed",
    fields: [
      {
        id: "curricula",
        inputType: "checkbox-group",
        question: "Which curricula/exam bodies can you teach?",
        options: [
          { value: "waec", label: "WAEC" },
          { value: "neco", label: "NECO" },
          { value: "jamb_utme", label: "JAMB/UTME" },
          { value: "cambridge_igcse", label: "Cambridge/IGCSE" },
          { value: "british_curriculum", label: "British Curriculum" },
        ],
        validation: { required: "Select at least one" },
      },
      {
        id: "grade_levels",
        inputType: "checkbox-group",
        question: "Which grade/class levels do you teach?",
        options: [
          { value: "primary", label: "Primary" },
          { value: "jss", label: "Junior Secondary (JSS1–3)" },
          { value: "sss", label: "Senior Secondary (SS1–3)" },
        ],
        validation: { required: "Select at least one" },
      },
    ],
  },
  {
    id: "teaching_profile",
    title: "Teaching style & profile",
    question: "Teaching style & profile",
    inputType: "mixed",
    fields: [
      {
        id: "bio",
        inputType: "text",
        htmlType: "textarea",
        question: "Tell students about yourself",
        placeholder: "Your teaching philosophy, what makes your classes engaging, what students can expect…",
        validation: {
          required: "Please write a short bio",
          minLength: { value: 20, message: "Bio should be at least 20 characters" },
        },
      },
      {
        id: "profile_photo",
        inputType: "photo-upload",
        question: "Profile photo (optional)",
        validation: {},
      },
      {
        id: "teaching_style",
        inputType: "checkbox-group",
        question: "How would you describe your teaching style?",
        options: [
          { value: "hands_on", label: "Hands-on/Practical" },
          { value: "lecture_based", label: "Lecture-based" },
          { value: "interactive", label: "Interactive/Discussion" },
          { value: "exam_focused", label: "Exam-focused/Drilling" },
          { value: "project_based", label: "Project-based" },
          { value: "storytelling", label: "Storytelling/Real-world examples" },
        ],
        validation: { required: "Select at least one" },
      },
    ],
  },
  {
    id: "availability",
    inputType: "component",
    title: "Set your availability",
    question: "When are you available to teach?",
  },
  {
    id: "bank",
    title: "Bank & payment details",
    question: "Bank & payment details",
    inputType: "mixed",
    fields: [
      {
        id: "bank_name",
        inputType: "select",
        question: "Bank name",
        options: [
          { value: "access", label: "Access Bank" },
          { value: "gtbank", label: "GTBank" },
          { value: "zenith", label: "Zenith Bank" },
          { value: "first_bank", label: "First Bank of Nigeria" },
          { value: "uba", label: "UBA" },
          { value: "fidelity", label: "Fidelity Bank" },
          { value: "union", label: "Union Bank" },
          { value: "stanbic_ibtc", label: "Stanbic IBTC" },
          { value: "sterling", label: "Sterling Bank" },
          { value: "wema", label: "Wema Bank" },
          { value: "polaris", label: "Polaris Bank" },
          { value: "ecobank", label: "Ecobank" },
          { value: "fcmb", label: "FCMB" },
          { value: "kuda", label: "Kuda Bank" },
          { value: "opay", label: "Opay" },
          { value: "palmpay", label: "PalmPay" },
          { value: "other", label: "Other" },
        ],
        validation: { required: "Select your bank" },
      },
      {
        id: "account_number",
        inputType: "text",
        htmlType: "number",
        question: "Account number",
        validation: {
          required: "Enter your account number",
          pattern: { value: /^\d{10}$/, message: "Enter a valid 10-digit account number" },
        },
      },
      {
        id: "account_name",
        inputType: "text",
        question: "Account holder name",
        helpText: "Must match the name on your registration for payout verification.",
        validation: { required: "Enter the account holder name" },
      },
    ],
  },
];
